#!/usr/bin/env python3
"""
generate-squid-conf.py - proxy-profiles から squid.conf を生成する

使い方:
  python3 generate-squid-conf.py [options]

オプション:
  --profiles-dir PATH  プロファイルディレクトリ (デフォルト: ~/.local/share/my-tasks/proxy-profiles)
  --output PATH        出力先 (デフォルト: stdout)
  --apply              /etc/squid/squid.conf に書き込み squid -k reconfigure を実行
"""

import argparse
import json
import subprocess
import sys
import tempfile
from pathlib import Path

DEFAULT_PROFILES_DIR = "~/.local/share/my-tasks/proxy-profiles"

HEADER = """# Auto-generated by generate-squid-conf.py
# Do not edit manually.

acl SSL_ports port 443
acl CONNECT method CONNECT
acl ai_net src 10.200.1.0/24

http_access deny CONNECT !SSL_ports
"""

FOOTER = """http_access deny all
"""


def load_profiles(profiles_dir: Path) -> list[dict]:
    profiles = []
    for p in sorted(profiles_dir.glob("*.json")):
        with open(p, encoding="utf-8") as f:
            profile = json.load(f)
        for key in ("profile_id", "port", "listen_address", "allowed_domains"):
            if key not in profile:
                print(f"警告: {p.name} に {key} がありません。スキップします。", file=sys.stderr)
                break
        else:
            profiles.append(profile)
    return profiles


def generate_conf(profiles: list[dict]) -> str:
    lines = [HEADER]
    for profile in profiles:
        lines.append(f"http_port {profile['listen_address']}:{profile['port']}")
    lines.append("")
    for profile in profiles:
        pid = profile["profile_id"]
        domains = " ".join(profile["allowed_domains"])
        lines.append(f"acl {pid}_domains dstdomain {domains}")
        lines.append(f"acl {pid}_port myport {profile['port']}")
        lines.append(f"http_access allow ai_net CONNECT {pid}_domains {pid}_port")
        lines.append("")
    lines.append(FOOTER)
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="proxy-profiles から squid.conf を生成する")
    parser.add_argument("--profiles-dir", default=DEFAULT_PROFILES_DIR,
                        help=f"プロファイルディレクトリ (デフォルト: {DEFAULT_PROFILES_DIR})")
    parser.add_argument("--output", default="-",
                        help="出力先ファイルパス (デフォルト: stdout)")
    parser.add_argument("--apply", action="store_true",
                        help="/etc/squid/squid.conf に書き込み squid -k reconfigure を実行")
    args = parser.parse_args()

    profiles_dir = Path(args.profiles_dir).expanduser().resolve()
    if not profiles_dir.is_dir():
        print(f"エラー: プロファイルディレクトリが見つかりません: {profiles_dir}", file=sys.stderr)
        sys.exit(1)

    profiles = load_profiles(profiles_dir)
    if not profiles:
        print("エラー: 有効なプロファイルがありません", file=sys.stderr)
        sys.exit(1)

    conf = generate_conf(profiles)

    if args.apply:
        output_path = Path("/etc/squid/squid.conf")
        with tempfile.NamedTemporaryFile(mode="w", suffix=".conf", delete=False) as tmp:
            tmp.write(conf)
            tmp_path = tmp.name
        result = subprocess.run(["squid", "-k", "parse", "-f", tmp_path],
                                capture_output=True, text=True)
        Path(tmp_path).unlink()
        if result.returncode != 0:
            print(f"エラー: squid 構文検証に失敗:\n{result.stderr}", file=sys.stderr)
            sys.exit(1)
        output_path.write_text(conf, encoding="utf-8")
        print(f"squid.conf を更新: {output_path}", file=sys.stderr)
        result = subprocess.run(["sudo", "squid", "-k", "reconfigure"],
                                capture_output=True, text=True)
        if result.returncode != 0:
            print(f"警告: squid reconfigure 失敗:\n{result.stderr}", file=sys.stderr)
        else:
            print("squid reconfigure 完了", file=sys.stderr)
    elif args.output == "-":
        print(conf, end="")
    else:
        Path(args.output).write_text(conf, encoding="utf-8")
        print(f"出力: {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
